# Generated by Django 5.2.4 on 2025-07-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_movie_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='desc',
            field=models.CharField(default='-', max_length=256),
        ),
    ]
